import './globals.css'
import type { Metadata } from 'next'

import { Providers } from './providers'
import { Prompt } from 'next/font/google'
import { SiteNav } from '@/components/site-nav'


const prompt = Prompt({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={prompt.className}>
       <body className="min-h-screen bg-background antialiased">
      <Providers>
        <SiteNav/>
        {children}
        </Providers>
        </body>
    </html>
  )
}
